[project]
name = "pyenergyplus"
version = "23.1.0"
description = "Direct port of pyenergyplus inside EnergyPlus to a standalone Python package."
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
